name: credit_risk_modeling
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas=1.5.3
  - scikit-learn
  - seaborn
  - ru
  - pytest
  - linearmodels
  - statsmodels
  - pip:
    - python-dotenv
    - mkdocs
    - pyampute
    - -e .