name: credit_risk_modeling
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - missingno
  - notebook
  - numpy
  - pandas=1.5.3
  - scikit-learn>=1.3
  - seaborn
  - scipy
  - statsmodels
  - rust
  - pytest
  - linearmodels
  - feature_engine
  - pytest = 7.2.2
  - imbalanced-learn>=0.11
  - pip:
    - python-dotenv
    - mkdocs
    - pyampute
    - -e .